fix yq version check
kubermatic/mla pull request #154
Opened 2023-02-15 18:09 UTC by toschneck

**What this PR does / why we need it**:
At my mac, the `yq --version` output is not matching the grep pattern.
```
yq --version
yq (https://github.com/mikefarah/yq/) version v4.30.8
```

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
fix yq 4 version check
```

**Documentation**:

```documentation
NONE
```

2023-02-15 18:10 UTC, toschneck commented
/assign @wurbanski

2023-02-15 18:21 UTC, wurbanski requested changes

2023-02-15 18:21 UTC, wurbanski commented on hack/fetch-chart-dependencies.sh
> +  yq --version | grep "version.*4" >/dev/null || (echo "yq version 3 not supported, exiting..."; exit 1)
This breaks the check on some 3.x versions, e.g.:
```
> yq --version | grep "version.*4"
yq version 3.4.1
```

2024-09-06 20:16 UTC, toschneck commented
not needed as mla is now installed via insaller

2024-09-06 20:16 UTC, closed without merging